services:
  certbot:
    image: ${IMG_REGISTRY:-bybatkhuu}/certbot:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    volumes:
      - "./volumes/storage/certbot/logs:/var/log/letsencrypt"
      - "./volumes/storage/certbot/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      - "./volumes/storage/certbot/ssl:/etc/letsencrypt"
    network_mode: host
    tty: true
    command: ["--renew=standalone"]
