services:
  certbot:
    image: bybatkhuu/certbot:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/certbot/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      - "./volumes/storage/certbot/ssl:/etc/letsencrypt"
    network_mode: host
    command: ["--renew=standalone"]
    tty: true
