version: "3.8"

services:
  certbot:
    image: ${CERTBOT_IMG_NAMESCAPE:-bybatkhuu}/certbot:${CERTBOT_IMG_VERSION:-latest}
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    volumes:
      - "./volumes/storage/certbot/ssl:/etc/letsencrypt"
      - "./volumes/storage/certbot/logs:/var/log/letsencrypt"
    tty: true
    network_mode: host
    command: ["--renew=standalone"]
