version: "3.8"

services:
  certbot:
    # env_file:
    #   - .env
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./scripts/docker/certbot-permissions.sh:/usr/local/bin/certbot-permissions.sh"
      # - "./volumes/storage/certbot/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      # - "./volumes/storage/certbot/secrets:/root/.secrets/certbot"
      # - "./volumes/storage/certbot/secrets:/root/.aws"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 256M
    # network_mode: bridge
    # ports:
    #   - "80:80"
    command: ["--renew=standalone"]
    # command: ["--new=webroot"]
    # command: ["--disable-renew"]
    # command: ["--dns=cloudflare"]
    # command: ["--dns=route53"]
    # command: ["--dns=google"]
    # command: ["--dns=godaddy"]
    # command: ["--dns=digitalocean"]
    # command: ["/bin/bash"]
