services:
  certbot:
    # env_file:
    #   - .env
    volumes:
      # - "./volumes/storage/certbot/secrets:/root/.secrets/certbot"
      # - "./volumes/storage/certbot/secrets:/root/.aws"
      - "./scripts/docker/certbot-permissions.sh:/usr/local/bin/certbot-permissions.sh"
      - "./scripts/docker/certbot-deploy-hook.sh:/usr/local/bin/certbot-deploy-hook.sh"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 256M
    # network_mode: bridge
    # ports:
    #   - "${CERTBOT_PORT:-80}:80"
    # command: ["--new=webroot"]
    # command: ["--renew=standalone"]
    # command: ["--disable-renew"]
    # command: ["--dns=cloudflare"]
    # command: ["--dns=digitalocean"]
    # command: ["--dns=route53"]
    # command: ["--dns=google"]
    # command: ["--dns=godaddy"]
    # command: ["/bin/bash"]
